### ISSUE TITLE
marine test : allow to control service lifecycle

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/marine-rs-sdk-test#6]
# Description

1. Declare 2 services form same wasm hash, so different file paths (my-service-1.wasm and my-service-2.wasm):
```toml
[[module]]
    name = "my-service-1"
    mem_pages_count = 1
    logger_enabled = true    
[[module]]
    name = "my-service-2"
    mem_pages_count = 1
    logger_enabled = true
```

2. Will get in code:
```rust
tests::flow::my_service_1_structs::__m_generated_my_service_1::MGeneratedStructmy_service_1
tests::flow::my_service_2_structs::__m_generated_my_service_2::MGeneratedStructmy_service_2
```

### Actual
Same wasm, 2 different Rust structs.
### Expected
Can instance same module API 2 times which share same Rust types.

# Solution:
```toml
[[module]]
    name = "my-service"
[[service]]
    name = "my-service_1"
    module = "my-service"
    mem_pages_count = 1
    logger_enabled = true
[[service]]
    name = "my-service_2"
    module = "my-service"
    mem_pages_count = 1
    logger_enabled = true    
```

In code 
```rust
let mut s =my_service_1::new();
s =my_service_2::new();
```

# Why?

I need test which checks replication logic.
